/**
 * The following base URL works if you are running the iOS simulator on your
 * computer. If you want to use your phone, replace 'localhost' with your IP
 * address. You can find your IP address using the following command:
 *
 * ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'
 *
 * So instead of 'http://localhost:8080' you have something like 'http://192.168.0.105:8080'
 *
 * A simpler way to get your LAN IP is to directly use the URL generated by Expo and replace the port by 8080
 */
const BASE_URL = `http://localhost:8080/`;

const MAP_REFRESH_RATE = 10000; // ms

export { BASE_URL, MAP_REFRESH_RATE };
